### ISSUE TITLE
Ubuntu_14_04_OCE_PythonOCC_Setup.sh  typos

### ISSUE THREAD

**Issue by ruminations** [jmwright/pythonocc_oce_setup#1]
line 11
"swig" is listed twice in the apt-get arguments

line 32
"Guild" should be "Build" in the comment

**Comment by jmwright** [comment]
@ruminations Thank you for contributing. I've included your changes in a new release, and have given you credit in the [changelog](https://github.com/jmwright/pythonocc_oce_setup/blob/master/changes.md).
